### ISSUE TITLE
Update addon for these sites also

### ISSUE THREAD

**Issue by ernilambar** [smjrifle/News-Reader-Firefox-Extension#1]
Nice work. It works with lots of Nepali news site. Can you please update addon to work on these sites also?

* https://www.sharesansar.com/
* http://www.bizshala.com/
* https://bizmandu.com/
* https://merolagani.com/
* http://sharelagani.com/

Thanks

**Comment by suniel** [comment]
Hajur dai. Thank you.
Yes we were looking for these list. Few issues haru ni xa. 
Probly Sunday new version push garxam hola.
